#!/usr/bin/env bash
# Modern media pipeline: VP9/WebM video sources (≈40-60% smaller than the MP4s,
# which stay as the universal fallback), AVIF stills, and tiny inline AVIF LQIP
# placeholders. Idempotent — skips outputs that already exist.
set -euo pipefail
cd "$(dirname "$0")/.."
A=public/assets
LQIP=src/lqip.generated.ts

vp9() { # $1 in.mp4  $2 out.webm
  [ -f "$2" ] && { echo "skip $2"; return; }
  echo "→ VP9 $2"
  ffmpeg -hide_banner -loglevel error -y -i "$1" \
    -c:v libvpx-vp9 -b:v 0 -crf 33 -row-mt 1 -deadline good -cpu-used 3 \
    -pix_fmt yuv420p -an "$2"
}

avif() { # $1 in.jpg  $2 out.avif
  [ -f "$2" ] && { echo "skip $2"; return; }
  echo "→ AVIF $2"
  avifenc --min 24 --max 36 -s 6 "$1" "$2" >/dev/null
}

vp9 $A/hero.mp4   $A/hero.webm
vp9 $A/middle.mp4 $A/middle.webm
vp9 $A/orbit.mp4  $A/orbit.webm

avif $A/g1.jpg $A/g1.avif
avif $A/g2.jpg $A/g2.avif
avif $A/g3.jpg $A/g3.avif

# ── Tiny inline AVIF LQIP: a ~24px blurred preview baked into a generated TS
#    module as a data URI, shown behind media until the real frame arrives.
echo "→ LQIP $LQIP"
{
  echo "// AUTO-GENERATED by scripts/encode-assets.sh — do not edit."
  echo "// Tiny inline AVIF previews (~24px) used as blur-up placeholders."
  echo "export const lqip: Record<string, string> = {"
  for f in hero_poster middle_poster g1 g2 g3; do
    tmp="$(mktemp --suffix=.avif)"
    ffmpeg -hide_banner -loglevel error -y -i "$A/$f.jpg" \
      -vf "scale=24:-1" -c:v libaom-av1 -crf 40 -still-picture 1 "$tmp"
    b64="$(base64 -w0 "$tmp")"
    rm -f "$tmp"
    echo "  '$f': 'data:image/avif;base64,$b64',"
  done
  echo "}"
} > "$LQIP"

echo "── sizes ──"
ls -lh $A/*.webm $A/*.avif 2>/dev/null | awk '{print $5"\t"$9}'
echo "done."
